# Generated by Django 2.1 on 2018-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(default='', max_length=500, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='will_learn',
            field=models.CharField(default='', max_length=500, verbose_name='将会学到'),
        ),
    ]
